apiVersion: istio.io/v1alpha1
kind: IstioConfig
metadata:
  name: route-rule-default-route
  namespace: default
spec:
  destination: reviews.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
